module.exports = {
  'PROJECT_CONTENT_TYPE': 1,
  'ARTICLE_CONTENT_TYPE': 2,
  'HOBBY_CONTENT_TYPE': 3,
  'WEB_CONTENT_TYPE': 4,

  'IMAGE_MEDIA_TYPE': 1,
  'PDF_MEDIA_TYPE': 2,
  'YOUTUBE_MEDIA_TYPE': 3,
  'WEB_PAGE_MEDIA_TYPE': 4,
};