module.exports = {
  // Media Types
  IMAGE_MEDIA_TYPE: 1,
  PDF_MEDIA_TYPE: 2,
  VIDEO_MEDIA_TYPE: 3,
  WEB_PAGE_MEDIA_TYPE: 4,

  // Content Types
  PROFILE_CONTENT_TYPE: 1,
  PROFESSIONAL_CONTENT_TYPE: 2,
  PERSONAL_CONTENT_TYPE: 3,
  RECREATIONAL_CONTENT_TYPE: 4,
};